apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blazor-workshop-starter
  annotations:
    github.com/project-slug: K3lly42/blazor-workshop-starter
spec:
  type: other
  lifecycle: unknown
  owner: admins
